# Generated by Django 4.2.7 on 2023-11-07 22:38

from django.db import migrations, models
from django.utils import timezone


def create_rxs(apps, schema_editor):
    """Create some fake RxFills to play around with
    """
    RxFill = apps.get_model('app', 'RxFill')
    rxs = [
        RxFill(
            created_dt=timezone.now(),
            modified_dt=timezone.now()
        )
        for _ in range(10)
    ]
    RxFill.objects.bulk_create(rxs)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RxFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField()),
                ('modified_dt', models.DateTimeField()),
                ('status', models.CharField(choices=[('SENT', 'SENT'), ('RECEIVED', 'RECEIVED'), ('PROCESSING', 'PROCESSING'), ('FILLED', 'FILLED'), ('PICKED UP', 'PICKED UP')], default='SENT')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_rxs)
    ]
